# Quick test pipeline:
# 
# This pipeline runs several example mechanisms to check for errors
# impacting basic functionality of kpp

# This pipeline triggers on commits to dev for now, but main may be
# added in the future. Commits to feature branches do not trigger 
# this pipeline, but open pull requests and commits to pull requests 
# do trigger a pipeline build.
trigger:
  branches:
    include:
      - dev*
      - patch*
      - bugfix*
      - tmp_MECCA_ci*
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-20.04'
# Login to Docker Hub, build the image, and push the built image
# to Docker Hub
steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      buildContext: $(Build.Repository.LocalPath)   # The path to the source code repo
      Dockerfile: .ci-pipelines/Dockerfile
      arguments: --progress=plain
