---
# ======================================================================
# ReadTheDocs environment file
#
# If you wish to build a Mamba/Conda environment with the dependencies
# needed for building the ReadTheDocs documentation, use:
#
# $ conda env create -n rtd_env --file=read_the_docs_environment.yml
# ======================================================================
name: rtd_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - docutils
  - jinja2
  - myst-parser
  - sphinx
  - sphinx-autobuild
  - sphinx-rtd-theme
  - sphinxcontrib-bibtex
